<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>plugins</artifactId>
        <groupId>org.igniterealtime.openfire</groupId>
        <version>5.1.2</version>
    </parent>
    
    <groupId>org.igniterealtime.openfire</groupId>
    <artifactId>pade</artifactId>
    <version>3.0.0-SNAPSHOT</version>	
    
    <name>Pade</name>
    <description>Web-based chat, groupchat, telephones, audio and video conferencing solution using ConverseJS, Galene, BroadcastBox and FreeSWITCH</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <sourceDirectory>src/java</sourceDirectory>
        <testSourceDirectory>src/test</testSourceDirectory>
        <plugins>                        
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
            </plugin>
			<plugin>
				<groupId>org.eclipse.jetty.ee8</groupId>
				<artifactId>jetty-ee8-jspc-maven-plugin</artifactId>
			</plugin>          
        </plugins>
    </build>

    <dependencies>   
        <dependency>
            <groupId>org.igniterealtime.openfire</groupId>
            <artifactId>xmppserver</artifactId>
            <version>${openfire.version}</version>
            <scope>provided</scope>
        </dependency>		
    </dependencies>
	
    <repositories>
        <repository>
            <id>igniterealtime</id>
            <name>Ignite Realtime Repository</name>
            <url>https://igniterealtime.org/archiva/repository/maven/</url>
        </repository>		
        <repository>
            <id>localLibs</id>
            <name>localLibs</name>
            <url>file://${project.basedir}/lib</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>true</enabled>
				<checksumPolicy>warn</checksumPolicy>
			</releases>			
        </repository>  	
		
    </repositories>

    <pluginRepositories>
        <!-- Typically used to retrieve Maven plugins that are used by this project.
             This apparently is also used to botain the dependencies _used by_ these
             plugins (such as the openfire-plugin-assembly-descriptor, needed to
             package the project as an Openfire plugin!) -->
        <pluginRepository>
            <id>igniterealtime</id>
            <name>Ignite Realtime Repository</name>
            <url>https://igniterealtime.org/archiva/repository/maven/</url>
        </pluginRepository>
    </pluginRepositories>   	
</project>
